### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by Thing3487** [blooketmastery/Blooket-Cheat-Codes#1]
This software is currently in violation of the [Stewart Private License](https://github.com/Minesraft2/Blooket-Cheats/blob/main/LICENSE), please take this down or further action will be taken.

**Comment by blooketmastery** [comment]
Huh

-Blooketmastery

**Comment by Thing3487** [comment]
> Huh
> […](#)

You stole the coode

**Comment by blooketmastery** [comment]
Who is this?
And what is the Stewart Private License?

-Blooketmastery

**Comment by Thing3487** [comment]
Just click on the text

**Comment by Thing3487** [comment]
and i’m a contributor to Minesraft2’s rep
